package com.yada.sdk.gcs.protocol.resp

import org.scalatest.{FlatSpec, Matchers}

/**
  * 根据卡号查询所有账户概要信息的响应测试
  */
class TS010102RespTest extends FlatSpec with Matchers {

  "TS010102 response xml" should "parse 100%" in {
    val respXML = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<GCS transactionID=\"010102\" isRequest=\"false\" isResponse=\"true\">\n    <system>\n        <prop key=\"transactionCode\" value=\"010102\"/>\n        <prop key=\"transactionNumber\" value=\"0020160318154242\"/>\n        <prop key=\"txnTraceNumber\" value=\"0011503507\"/>\n        <prop key=\"transactionSessionId\" value=\"93c4399ad67d925fa40d0693adb0a222\"/>\n        <prop key=\"requestChannelId\" value=\"WX01\"/>\n        <prop key=\"txnBankCode\" value=\"003\"/>\n        <prop key=\"txnProvinceCode\" value=\"\"/>\n        <prop key=\"txnBranchCode\" value=\"00003\"/>\n        <prop key=\"txnCounterCode\" value=\"\"/>\n        <prop key=\"txnTerminalCode\" value=\"\"/>\n        <prop key=\"txnUserCode\" value=\"wx00000\"/>\n        <prop key=\"localBankTxnRequestTime\" value=\"15:40:37\"/>\n        <prop key=\"localBankTxnRequestDate\" value=\"2016-03-18\"/>\n        <prop key=\"localBankTxnResponseTime\" value=\"15:40:37\"/>\n        <prop key=\"localBankTxnResponseDate\" value=\"2016-03-18\"/>\n        <prop key=\"bocBankTxnRequestTime\" value=\"15:40:37\"/>\n        <prop key=\"bocBankTxnRequestDate\" value=\"2016-03-18\"/>\n        <prop key=\"bocBankTxnResponseTime\" value=\"15:40:37\"/>\n        <prop key=\"bocBankTxnResponseDate\" value=\"2016-03-18\"/>\n        <prop key=\"returnCode\" value=\"+GC00000\"/>\n        <prop key=\"returnMessage\" value=\"Success\"/>\n    </system>\n    <page key=\"RP010102\">\n        <list key=\"RP010101\" entityKey=\"accountList\" size=\"2\">\n            <entity>\n                <prop key=\"accountId\" value=\"001A0213064FF77E\"/>\n                <prop key=\"accountRefNo\" value=\"2861695039487302\"/>\n                <prop key=\"automaticStatusCode\" value=\"\"/>\n                <prop key=\"automaticStatusSetDate\" value=\"\"/>\n                <prop key=\"currencyCode\" value=\"CNY\"/>\n                <prop key=\"institutionId\" value=\"BOCK\"/>\n                <prop key=\"issuingBranchId\" value=\"\"/>\n                <prop key=\"manualStatusCode\" value=\"NORM\"/>\n                <prop key=\"manualStatusSetDate\" value=\"\"/>\n                <prop key=\"productType\" value=\"PRMC\"/>\n            </entity>\n            <entity>\n                <prop key=\"accountId\" value=\"001A0213064FF780\"/>\n                <prop key=\"accountRefNo\" value=\"7821440695701839\"/>\n                <prop key=\"automaticStatusCode\" value=\"\"/>\n                <prop key=\"automaticStatusSetDate\" value=\"\"/>\n                <prop key=\"currencyCode\" value=\"USD\"/>\n                <prop key=\"institutionId\" value=\"BOCK\"/>\n                <prop key=\"issuingBranchId\" value=\"\"/>\n                <prop key=\"manualStatusCode\" value=\"NORM\"/>\n                <prop key=\"manualStatusSetDate\" value=\"\"/>\n                <prop key=\"productType\" value=\"PRMC\"/>\n            </entity>\n        </list>\n    </page>\n</GCS>"
    val resp = new TS010102Resp(respXML)

  }
}
