package cn.com.boc.gcs;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.7.6 2013-08-05T11:07:48.256+08:00
 * Generated source version: 2.7.6
 */

@WebFault(name = "GatewayException", targetNamespace = "www.boc.com.cn/gcs")
public class GatewayException_Exception extends Exception {

	private static final long serialVersionUID = 180804588400642839L;
	private cn.com.boc.gcs.GatewayException gatewayException;

	public GatewayException_Exception() {
		super();
	}

	public GatewayException_Exception(String message) {
		super(message);
	}

	public GatewayException_Exception(String message, Throwable cause) {
		super(message, cause);
	}

	public GatewayException_Exception(String message, cn.com.boc.gcs.GatewayException gatewayException) {
		super(message);
		this.gatewayException = gatewayException;
	}

	public GatewayException_Exception(String message, cn.com.boc.gcs.GatewayException gatewayException, Throwable cause) {
		super(message, cause);
		this.gatewayException = gatewayException;
	}

	public cn.com.boc.gcs.GatewayException getFaultInfo() {
		return this.gatewayException;
	}
}
