package cn.com.boc.gcs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6 2013-08-05T11:07:48.263+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "www.boc.com.cn/gcs", name = "Gateway")
public interface Gateway {

	@WebResult(name = "response", targetNamespace = "")
	@RequestWrapper(localName = "service", targetNamespace = "www.boc.com.cn/gcs", className = "cn.com.boc.gcs.Service")
	@WebMethod
	@ResponseWrapper(localName = "serviceResponse", targetNamespace = "www.boc.com.cn/gcs", className = "cn.com.boc.gcs.ServiceResponse")
	public String service(@WebParam(name = "request", targetNamespace = "") String request)
			throws GatewayException_Exception;
}
